### ISSUE TITLE
On Release Build, printer 🖨 is not printing

### ISSUE THREAD

**Issue by amosogra** [402d/RawbtAPI#1]
On debug build, it works flawlessly, but on release build this error message was printed as toast: **"Empty print job"**
I have tried all possible ways but to no avail.

Kotlin version: 1.6.10
min sdk: 21
target sdk: 33
AGP: 7.2.1
Gradle: 7.4.2

Please help me resolve this issue

**Comment by Muraveiko** [comment]
https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg

**Comment by Muraveiko** [comment]
IF your build.gradle(:app) mihify & shrink ?  
```
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
```
THEN 
add in your project 
proguard-rules.pro:
```
-keep class rawbt.** { *; }
```

**Comment by Muraveiko** [comment]
update
implementation 'com.github.402d:RawbtAPI:9238fdefc6'

Is it help (without strings from previus answer)?

**Comment by amosogra** [comment]
> IF your build.gradle(:app) mihify & shrink ?
> 
> ```
>     buildTypes {
>         release {
>             minifyEnabled true
>             shrinkResources true
>             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>         }
>     }
> ```
> 
> THEN add in your project proguard-rules.pro:
> 
> ```
> -keep class rawbt.** { *; }
> ```

Thank you 😊 
Issue solved 
Proguard was the problem

**Comment by amosogra** [comment]
> update implementation 'com.github.402d:RawbtAPI:9238fdefc6'
> 
> Is it help (without strings from previus answer)?

The previous answer solved it for me. Thank you 😊

**Comment by amosogra** [comment]
BTW I crested a Flutter plugin for android with this library. 

[Check it out ✔ ](https://github.com/amosogra/printer)
